Repository octokit/octokit.net, pull requests merged in 2018-07, with the labels that each got.

#1838 Fix ThrowsAsync tests that were not being awaited
  Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
  Octokit.Tests/Clients/GitHubAppsClientTests.cs
Labels: skip-release-notes

#1843 Update github-apps.md
  docs/github-apps.md
Labels: skip-release-notes

#1842 Implement new Project Card archiving
  Octokit.Reactive/Clients/IObservableProjectCardsClient.cs
  Octokit.Reactive/Clients/ObservableProjectCardsClient.cs
  Octokit.Tests.Integration/Clients/ProjectCardsClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableProjectCardsClientTests.cs
  Octokit.Tests/Clients/ProjectCardsClientTests.cs
  Octokit.Tests/Models/ProjectCardRequestTests.cs
  Octokit.Tests/Reactive/ObservableProjectCardsClientTests.cs
  Octokit/Clients/IProjectCardsClient.cs
  Octokit/Clients/ProjectCardsClient.cs
  Octokit/Models/Request/ProjectCardRequest.cs
  Octokit/Models/Request/ProjectCardUpdate.cs
  Octokit/Models/Response/ProjectCard.cs
  appveyor.yml
Labels: category: feature

#1846 Implement Check Suites API
  Octokit.Reactive/Clients/IObservableCheckSuitesClient.cs
  Octokit.Reactive/Clients/IObservableChecksClient.cs
  Octokit.Reactive/Clients/ObservableCheckSuitesClient.cs
  Octokit.Reactive/Clients/ObservableChecksClient.cs
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit.Tests.Integration/Clients/CheckSuitesClientTests.cs
  Octokit.Tests.Integration/Clients/GitHubAppsClientTests.cs
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests.Integration/Reactive/ObservableCheckSuitesClientTests.cs
  Octokit.Tests/Clients/CheckSuitesClientTests.cs
  Octokit.Tests/Clients/ChecksClientTests.cs
  Octokit.Tests/Clients/EventsClientTests.cs
  Octokit.Tests/Helpers/MockedIApiConnection.cs
  Octokit.Tests/Models/CheckSuiteEventTests.cs
  Octokit.Tests/Reactive/ObservableCheckSuitesClientTests.cs
  Octokit.Tests/Reactive/ObservableChecksClientTests.cs
  Octokit/Clients/CheckSuitesClient.cs
  Octokit/Clients/ChecksClient.cs
  Octokit/Clients/ICheckSuitesClient.cs
  Octokit/Clients/IChecksClient.cs
  Octokit/GitHubClient.cs
  Octokit/Helpers/AcceptHeaders.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Http/SimpleJsonSerializer.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Common/CheckStatus.cs
  Octokit/Models/Common/CheckSuitePreferenceAutoTrigger.cs
  Octokit/Models/Common/CheckSuitePreferences.cs
  Octokit/Models/Request/CheckSuiteRequest.cs
  Octokit/Models/Request/CheckSuiteTriggerRequest.cs
  Octokit/Models/Request/NewCheckSuite.cs
  Octokit/Models/Response/ActivityPayloads/CheckSuiteEventPayload.cs
  Octokit/Models/Response/CheckSuite.cs
  Octokit/Models/Response/CheckSuitePreferencesResponse.cs
  Octokit/Models/Response/CheckSuitesResponse.cs
  Octokit/Models/Response/InstallationPermissions.cs
  script/configure-integration-tests.ps1
Labels: category: feature

#1845 Added 'Archived' flag to Repository response.
  Octokit/Models/Request/RepositoryUpdate.cs
  Octokit/Models/Request/SearchIssuesRequest.cs
  Octokit/Models/Request/SearchRepositoriesRequest.cs
  Octokit/Models/Response/Repository.cs
Labels: category: feature

#1847 Implement Check Runs API
  Octokit.Reactive/Clients/IObservableCheckRunsClient.cs
  Octokit.Reactive/Clients/IObservableChecksClient.cs
  Octokit.Reactive/Clients/ObservableCheckRunsClient.cs
  Octokit.Reactive/Clients/ObservableChecksClient.cs
  Octokit.Tests.Integration/Clients/CheckRunsClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs
  Octokit.Tests/Clients/CheckRunsClientTests.cs
  Octokit.Tests/Clients/EventsClientTests.cs
  Octokit.Tests/Models/CheckRunEventTests.cs
  Octokit.Tests/Reactive/ObservableCheckRunsClientTests.cs
  Octokit.Tests/Reactive/ObservableCheckSuitesClientTests.cs
  Octokit/Clients/CheckRunsClient.cs
  Octokit/Clients/ChecksClient.cs
  Octokit/Clients/ICheckRunsClient.cs
  Octokit/Clients/ICheckSuitesClient.cs
  Octokit/Clients/IChecksClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Http/SimpleJsonSerializer.cs
  Octokit/Models/Common/CheckStatus.cs
  Octokit/Models/Request/CheckRunRequest.cs
  Octokit/Models/Request/CheckRunUpdate.cs
  Octokit/Models/Request/NewCheckRun.cs
  Octokit/Models/Request/NewCheckRunAction.cs
  Octokit/Models/Request/NewCheckRunAnnotation.cs
  Octokit/Models/Request/NewCheckRunImage.cs
  Octokit/Models/Request/NewCheckRunOutput.cs
  Octokit/Models/Request/NewCheckSuite.cs
  Octokit/Models/Response/ActivityPayloads/CheckRunEventPayload.cs
  Octokit/Models/Response/CheckRun.cs
  Octokit/Models/Response/CheckRunAnnotation.cs
  Octokit/Models/Response/CheckRunOutputResponse.cs
  Octokit/Models/Response/CheckRunsResponse.cs
  Octokit/Models/Response/CheckSuite.cs
Labels: category: feature

#1851 Release v0.31 - Check yo' self!
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Tests.Integration/Clients/CheckRunsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryHooksClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs
  Octokit.Tests/Clients/CheckRunsClientTests.cs
  Octokit.Tests/Clients/ProjectCardsClientTests.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Models/RepositoryTransferTest.cs
  Octokit.Tests/Reactive/ObservableCheckRunsClientTests.cs
  Octokit.Tests/Reactive/ObservableCheckSuitesClientTests.cs
  Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
  Octokit/Helpers/Ensure.cs
  Octokit/Models/Request/CheckRunUpdate.cs
  Octokit/Models/Request/CheckSuiteTriggerRequest.cs
  Octokit/Models/Request/NewCheckRun.cs
  Octokit/Models/Request/NewCheckSuite.cs
  Octokit/Models/Response/CheckRunOutputResponse.cs
  Octokit/Models/Response/EventInfo.cs
  ReleaseNotes.md
Labels: skip-release-notes

#1852 Fixes check runs taking over 2017 years to complete
  Octokit/Models/Request/CheckRunUpdate.cs
  Octokit/Models/Request/NewCheckRun.cs
Labels: category: bug
