Repository octokit/octokit.net, pull requests merged in 2018-06, with the labels that each got.

#1805 Correct upload asset code
  docs/releases.md
Labels: category: docs-and-samples

#1819 Mentioning the reset time is based on UTC standard
  docs/getting-started.md
Labels: category: docs-and-samples

#1818 A missing event state: comment_deleted
  Octokit/Models/Response/EventInfo.cs
Labels: category: feature

#1822 Remove runtime dependency on SourceLink.Create.GitHub
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit/Octokit.csproj
Labels: category: housekeeping

#1831 Fix exception in RepositoriesClient.GetAllLanguages() when no languages exist
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit/Clients/RepositoriesClient.cs
Labels: category: bug

#1806 add GraphQL Node ID's to response models
  Octokit.Tests/Models/MigrationTests.cs
  Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
  Octokit/Models/Common/Committer.cs
  Octokit/Models/Response/Account.cs
  Octokit/Models/Response/Author.cs
  Octokit/Models/Response/Blob.cs
  Octokit/Models/Response/Commit.cs
  Octokit/Models/Response/CommitComment.cs
  Octokit/Models/Response/CommitStatus.cs
  Octokit/Models/Response/Deployment.cs
  Octokit/Models/Response/DeploymentStatus.cs
  Octokit/Models/Response/EventInfo.cs
  Octokit/Models/Response/Gist.cs
  Octokit/Models/Response/GistComment.cs
  Octokit/Models/Response/GistFork.cs
  Octokit/Models/Response/GitHubCommit.cs
  Octokit/Models/Response/GitReference.cs
  Octokit/Models/Response/GitTag.cs
  Octokit/Models/Response/Issue.cs
  Octokit/Models/Response/IssueComment.cs
  Octokit/Models/Response/IssueEvent.cs
  Octokit/Models/Response/Label.cs
  Octokit/Models/Response/License.cs
  Octokit/Models/Response/LicenseMetadata.cs
  Octokit/Models/Response/Merge.cs
  Octokit/Models/Response/Migration.cs
  Octokit/Models/Response/Milestone.cs
  Octokit/Models/Response/Organization.cs
  Octokit/Models/Response/OrganizationMembershipInvitation.cs
  Octokit/Models/Response/Project.cs
  Octokit/Models/Response/ProjectCard.cs
  Octokit/Models/Response/ProjectColumn.cs
  Octokit/Models/Response/PullRequest.cs
  Octokit/Models/Response/PullRequestCommit.cs
  Octokit/Models/Response/PullRequestReview.cs
  Octokit/Models/Response/PullRequestReviewComment.cs
  Octokit/Models/Response/Reaction.cs
  Octokit/Models/Response/Reference.cs
  Octokit/Models/Response/Release.cs
  Octokit/Models/Response/ReleaseAsset.cs
  Octokit/Models/Response/Repository.cs
  Octokit/Models/Response/RepositoryContributor.cs
  Octokit/Models/Response/RepositoryInvitation.cs
  Octokit/Models/Response/RepositoryTag.cs
  Octokit/Models/Response/TagObject.cs
  Octokit/Models/Response/Team.cs
  Octokit/Models/Response/TimelineEventInfo.cs
  Octokit/Models/Response/User.cs
Labels: category: feature

#1824 Attempt to clarify GitHubApp docs
  docs/github-apps.md
Labels: category: docs-and-samples
