Repository octokit/octokit.net, pull requests merged in 2018-04, with the labels that each got.

#1791 Add csharp hint to code blocks
  docs/git-database.md
  docs/issues.md
  docs/labels.md
  docs/oauth-flow.md
  docs/releases.md
Labels: category: docs-and-samples

#1738 Adding initial support for GitHub Apps.
  .travis.yml
  Octokit.Reactive/Clients/IObservableGitHubAppsClient.cs
  Octokit.Reactive/Clients/ObservableGitHubAppsClient.cs
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit.Tests.Conventions/Exception/InvalidUrlPropertyTypeException.cs
  Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
  Octokit.Tests.Integration/Clients/GitHubAppsClientTests.cs
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests.Integration/Helpers/GitHubAppsTestAttribute.cs
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Clients/GitHubAppsClientTests.cs
  Octokit.Tests/Octokit.Tests.csproj
  Octokit/Authentication/AuthenticationType.cs
  Octokit/Authentication/Authenticator.cs
  Octokit/Authentication/BearerTokenAuthenticator.cs
  Octokit/Clients/GitHubAppsClient.cs
  Octokit/Clients/IGitHubAppsClient.cs
  Octokit/GitHubClient.cs
  Octokit/Helpers/AcceptHeaders.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Http/Connection.cs
  Octokit/Http/Credentials.cs
  Octokit/Http/IConnection.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Response/AccessToken.cs
  Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs
  Octokit/Models/Response/GitHubApp.cs
  Octokit/Models/Response/Installation.cs
  Octokit/Models/Response/InstallationId.cs
  Octokit/Models/Response/InstallationPermissions.cs
  Octokit/Octokit.csproj
  Octokit/SimpleJson.cs
  appveyor.yml
  build.ps1
  build.sh
  build/.vscode/launch.json
  build/.vscode/tasks.json
  build/Tasks/Build.cs
  docs/github-apps.md
  mkdocs.yml
  script/cibuild.ps1
  script/configure-integration-tests.ps1
Labels: category: feature

#1784 Build/Test projects to use .NET Core SDK 2.0.x
  .travis.yml
  Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Octokit.Tests.csproj
  build.ps1
  build/Build.csproj
  build/Context.cs
Labels: category: housekeeping

#1780 Remove method/members previously deprecated
  Octokit.Reactive/Clients/IObservableOrganizationsClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
  Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
  Octokit.Reactive/Clients/IObservableRepositoryTrafficClient.cs
  Octokit.Reactive/Clients/IObservableTeamsClient.cs
  Octokit.Reactive/Clients/ObservableOrganizationsClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryTrafficClient.cs
  Octokit.Reactive/Clients/ObservableTeamsClient.cs
  Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
  Octokit.Tests.Integration/Clients/TeamsClientTests.cs
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests/Clients/OrganizationsClientTests.cs
  Octokit.Tests/Clients/TeamsClientTests.cs
  Octokit.Tests/Reactive/ObservableOrganizationsClientTests.cs
  Octokit/Clients/IOrganizationsClient.cs
  Octokit/Clients/IPullRequestsClient.cs
  Octokit/Clients/IRepositoryBranchesClient.cs
  Octokit/Clients/IRepositoryTrafficClient.cs
  Octokit/Clients/ITeamsClient.cs
  Octokit/Clients/OrganizationsClient.cs
  Octokit/Clients/PullRequestsClient.cs
  Octokit/Clients/RepositoryBranchesClient.cs
  Octokit/Clients/RepositoryTrafficClient.cs
  Octokit/Clients/TeamsClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Request/BranchProtectionUpdate.cs
  Octokit/Models/Request/IssueUpdate.cs
  Octokit/Models/Request/NewIssue.cs
  Octokit/Models/Request/UpdateTeam.cs
  Octokit/Models/Response/TeamMembership.cs
Labels: category: housekeeping

#1778 Clarifies usage of reference in IReferencesClient methods
  Octokit.Reactive/Clients/IObservableReferencesClient.cs
  Octokit.Reactive/Clients/ObservableReferencesClient.cs
  Octokit/Clients/IReferencesClient.cs
  Octokit/Clients/ReferencesClient.cs
Labels: category: docs-and-samples

#1771 Adds MaintainerCanModify to PullRequest
  Octokit/Models/Request/NewPullRequest.cs
  Octokit/Models/Request/PullRequestUpdate.cs
  Octokit/Models/Response/PullRequest.cs
Labels: category: feature

#1795 Add proper accept header to all team calls (Fixes #1794)
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Clients/RepositoryBranchesClient.cs
Labels: category: feature

#1798 Adding a convention test to detect whether a model has a constructor exposing all properties
  Octokit.Tests.Conventions/Exception/MissingPublicConstructorWithAllPropertiesException.cs
  Octokit.Tests.Conventions/ModelTests.cs
  Octokit.Tests/Clients/AuthorizationsClientTests.cs
  Octokit.Tests/Models/PunchCardTests.cs
  Octokit.Tests/Reactive/AuthorizationExtensionsTests.cs
  Octokit/Helpers/ExcludeFromCtorWithAllPropertiesConventionTestAttribute.cs
  Octokit/Http/RateLimit.cs
  Octokit/Models/Response/Activity.cs
  Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs
  Octokit/Models/Response/ApplicationAuthorization.cs
  Octokit/Models/Response/Authorization.cs
  Octokit/Models/Response/BranchProtection.cs
  Octokit/Models/Response/CollaboratorPermission.cs
  Octokit/Models/Response/Commit.cs
  Octokit/Models/Response/CommitComment.cs
  Octokit/Models/Response/Deployment.cs
  Octokit/Models/Response/DeploymentStatus.cs
  Octokit/Models/Response/GitTag.cs
  Octokit/Models/Response/GpgKey.cs
  Octokit/Models/Response/Issue.cs
  Octokit/Models/Response/IssueComment.cs
  Octokit/Models/Response/Merge.cs
  Octokit/Models/Response/Organization.cs
  Octokit/Models/Response/Page.cs
  Octokit/Models/Response/PullRequestReviewComment.cs
  Octokit/Models/Response/PunchCard.cs
  Octokit/Models/Response/ReactionSummary.cs
  Octokit/Models/Response/Reference.cs
  Octokit/Models/Response/RenameInfo.cs
  Octokit/Models/Response/SourceInfo.cs
  Octokit/Models/Response/Team.cs
  Octokit/Models/Response/TeamMembershipDetails.cs
  Octokit/Models/Response/User.cs
  Octokit/Models/Response/Verification.cs
Labels: category: housekeeping
