Repository octokit/octokit.net, pull requests merged in 2019-09, with the labels that each got.

#1954 Add a warning to the statistics client about caching
  Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/IObservableStatisticsClient.cs
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/ObservableStatisticsClient.cs
  Octokit/Clients/IRepositoriesClient.cs
  Octokit/Clients/IStatisticsClient.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Clients/StatisticsClient.cs
Labels: category: bug

#1988 fix timezone offset handling
  Octokit.Tests/Clients/SearchClientTests.cs
  Octokit.Tests/Models/SearchIssuesRequestTests.cs
  Octokit/Models/Request/SearchRepositoriesRequest.cs
Labels: category: bug

#1996 update travis to use a recent .NET Core version when testing
  .travis.yml
Labels: category: housekeeping

#1998 add license metadata to package outputs
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit/Octokit.csproj
Labels: category: housekeeping, skip-release-notes

#2001 add net46 build output to package
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Octokit.Tests.csproj
  Octokit/Octokit.csproj
Labels: category: housekeeping, skip-release-notes

#1866 Generate code coverage output with coverlet
  .gitignore
  README.md
  appveyor.yml
  build/Build.csproj
  build/Context.cs
  build/Lifetime.cs
  build/Tasks/Clean.cs
  build/Tasks/CodeCoverage.cs
  build/Tasks/Package.cs
  build/Tools/Coverlet.cs
  build/Utilities/BuildVersion.cs
  codecov.yml
Labels: category: housekeeping

#2005 no need to build and run tests against net46
  Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Octokit.Tests.csproj
Labels: category: housekeeping, skip-release-notes

#2004 next set of tidy up of test warnings
  Octokit.Tests.Integration/Clients/MigrationsClientTests.cs
  Octokit.Tests/Http/ApiInfoParserTests.cs
  Octokit.Tests/Http/ApiInfoTests.cs
  Octokit.Tests/Http/ConnectionTests.cs
  Octokit.Tests/Http/JsonHttpPipelineTests.cs
  Octokit.Tests/Http/RateLimitTests.cs
  Octokit.Tests/Http/RedirectHandlerTests.cs
  Octokit.Tests/Models/NewReferenceTests.cs
  Octokit.Tests/Reactive/ObservableDeploymentStatusClientTests.cs
Labels: category: housekeeping, skip-release-notes

#2006 add netstandard2.0 output
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit/Octokit.csproj
Labels: category: housekeeping

#2009 Implement Draft Pull Requests
  Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
  Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
  Octokit.Tests/Clients/PullRequestsClientTests.cs
  Octokit.Tests/Reactive/ObservablePullRequestsClientTests.cs
  Octokit/Clients/PullRequestsClient.cs
  Octokit/Helpers/AcceptHeaders.cs
  Octokit/Models/Request/NewPullRequest.cs
  Octokit/Models/Response/PullRequest.cs
Labels: category: feature

#2010 Begin implementation of Enterprise ManagementConsole API, redux
  Octokit.Reactive/Clients/Enterprise/IObservableEnterpriseClient.cs
  Octokit.Reactive/Clients/Enterprise/IObservableEnterpriseManagementConsoleClient.cs
  Octokit.Reactive/Clients/Enterprise/ObservableEnterpriseClient.cs
  Octokit.Reactive/Clients/Enterprise/ObservableEnterpriseManagementConsoleClient.cs
  Octokit.Tests.Integration/Clients/Enterprise/EnterpriseManagementConsoleClientTests.cs
  Octokit.Tests.Integration/EnterpriseHelper.cs
  Octokit.Tests.Integration/Helpers/GitHubEnterpriseManagementConsoleTestAttribute.cs
  Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
  Octokit.Tests.Integration/Helpers/MaintenanceModeContext.cs
  Octokit.Tests/Clients/Enterprise/EnterpriseManagementConsoleClientTests.cs
  Octokit.Tests/Reactive/Enterprise/ObservableEnterpriseManagementConsoleClientTests.cs
  Octokit/Clients/Enterprise/EnterpriseClient.cs
  Octokit/Clients/Enterprise/EnterpriseManagementConsoleClient.cs
  Octokit/Clients/Enterprise/IEnterpriseClient.cs
  Octokit/Clients/Enterprise/IEnterpriseManagementConsoleClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Helpers/ReferenceExtensions.cs
  Octokit/Models/Request/Enterprise/UpdateMaintenanceRequest.cs
  Octokit/Models/Request/FormUrlEncodedParameters.cs
  Octokit/Models/Response/Enterprise/AdminStats.cs
  Octokit/Models/Response/Enterprise/AdminStatsComments.cs
  Octokit/Models/Response/Enterprise/AdminStatsGists.cs
  Octokit/Models/Response/Enterprise/AdminStatsHooks.cs
  Octokit/Models/Response/Enterprise/AdminStatsIssues.cs
  Octokit/Models/Response/Enterprise/AdminStatsMilestones.cs
  Octokit/Models/Response/Enterprise/AdminStatsOrgs.cs
  Octokit/Models/Response/Enterprise/AdminStatsPages.cs
  Octokit/Models/Response/Enterprise/AdminStatsPulls.cs
  Octokit/Models/Response/Enterprise/AdminStatsRepos.cs
  Octokit/Models/Response/Enterprise/AdminStatsUsers.cs
  Octokit/Models/Response/Enterprise/LdapSyncResponse.cs
  Octokit/Models/Response/Enterprise/LicenseInfo.cs
  Octokit/Models/Response/Enterprise/MaintenanceModeActiveProcesses.cs
  Octokit/Models/Response/Enterprise/MaintenanceModeResponse.cs
  Octokit/Models/Response/Enterprise/SearchIndexingResponse.cs
  docs/enterprise-administration.md
  script/configure-integration-tests.ps1
Labels: category: feature

#2012 tidy up new tests
  Octokit.Tests.Integration/Clients/Enterprise/EnterpriseManagementConsoleClientTests.cs
  Octokit.Tests.Integration/Helpers/GitHubEnterpriseManagementConsoleTestAttribute.cs
Labels: category: housekeeping, skip-release-notes
