Repository octokit/octokit.net, pull requests merged in 2019-02, with the labels that each got.

#1944 adding example for creating PR from fork
  docs/demos/exploring-pull-requests.md
Labels: category: docs-and-samples

#1949 Add pagination support to Migrations client
  Octokit.Reactive/Clients/IObservableMigrationsClient.cs
  Octokit.Reactive/Clients/ObservableMigrationsClient.cs
  Octokit.Tests.Integration/Clients/MigrationsClientTests.cs
  Octokit.Tests/Clients/MigrationsClientTests.cs
  Octokit.Tests/Reactive/ObservableMigrationsClientTests.cs
  Octokit/Clients/IMigrationsClient.cs
  Octokit/Clients/MigrationsClient.cs
Labels: category: feature

#1948 Pagination support to Reactions Clients
  Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/IssueCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/IssueReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
  Octokit.Tests/Clients/CommitCommentReactionsClientTests.cs
  Octokit.Tests/Clients/IssueCommentReactionsClientTests.cs
  Octokit.Tests/Clients/IssueReactionsClientTests.cs
  Octokit.Tests/Clients/PullRequestReviewCommentReactionsClientTests.cs
  Octokit.Tests/Reactive/ObservableCommitCommentReactionsClientTests.cs
  Octokit.Tests/Reactive/ObservableIssueCommentReactionsClientTests.cs
  Octokit.Tests/Reactive/ObservableIssueReactionsClientTests.cs
  Octokit.Tests/Reactive/ObservablePullRequestReviewCommentReactionsClientTests.cs
  Octokit/Clients/CommitCommentReactionsClient.cs
  Octokit/Clients/ICommitCommentReactionsClient.cs
  Octokit/Clients/IIssueCommentReactionsClient.cs
  Octokit/Clients/IIssueReactionsClient.cs
  Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/IssueCommentReactionsClient.cs
  Octokit/Clients/IssueReactionsClient.cs
  Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
Labels: category: feature

#1936 Don't apply Tls1.2 workaround when .NET 4.7 SystemDefault is set
  Octokit/Http/HttpClientAdapter.cs
Labels: category: bug
