Repository octokit/octokit.net, pull requests merged in 2020-02, with the labels that each got.

#2090 add IsTemplate field repository response model
  Octokit/Models/Response/Repository.cs
Labels: category: bug

#2091 ensure datetime offset is encoded correctly for search APIs
  Octokit.Tests.Integration/Clients/SearchClientTests.cs
  Octokit.Tests/Clients/SearchClientTests.cs
  Octokit/Models/Request/SearchRepositoriesRequest.cs
Labels: category: bug

#2105 improve handling of GetAllContentsByRef where root path is requested
  Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
  Octokit/Clients/RepositoryContentsClient.cs
Labels: category: bug

#2109 move dotnet-format global tool out of Lifetime
  .config/dotnet-tools.json
  build/Context.cs
  build/Lifetime.cs
  build/Tasks/FormatCode.cs
Labels: category: housekeeping

#2111 drop development versioning rules
  GitVersion.yml
Labels: skip-release-notes

#1716 Update MiscellaneousClient to ApiClient approach and add pagination support to GetAllLicenses.
  Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs
  Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs
  Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs
  Octokit.Tests/Clients/MiscellaneousClientTests.cs
  Octokit.Tests/Reactive/ObservableMiscellaneousClientTests.cs
  Octokit/Clients/IMiscellaneousClient.cs
  Octokit/Clients/MiscellaneousClient.cs
  Octokit/GitHubClient.cs
  Octokit/Helpers/ApiUrls.cs
Labels: category: housekeeping

#2114 Add Rocket and Eyes emoji reactions
  Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
  Octokit/Models/Response/Reaction.cs
Labels: category: bug
