Repository octokit/octokit.net, pull requests merged in 2021-02, with the labels that each got.

#2291 Add support for multi users and orgs in SearchCodeRequest
  Octokit.Tests.Integration/Clients/SearchClientTests.cs
  Octokit.Tests/Clients/SearchClientTests.cs
  Octokit/Models/Request/SearchCodeRequest.cs
  docs/search.md
Labels: category: bug

#2224 Fix property types in PullRequestCommit
  Octokit.Tests/Models/PullRequestCommitTests.cs
  Octokit/Models/Response/PullRequestCommit.cs
Labels: category: bug

#2299 tidy up workflow to address new restrictions
  .github/workflows/publish.yml
Labels: category: housekeeping

#2300 tidy up unused dependabot ignore rule
  .github/dependabot.yml
Labels: category: housekeeping

#2294 Move the build to .net 5
  .github/workflows/netcore.yml
  .github/workflows/publish.yml
  global.json
Labels: category: housekeeping

#2246 [Approved] Add repository topics
  Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests.Integration/Clients/SearchClientTests.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/SearchClientTests.cs
  Octokit.Tests/Models/RepositoryTopicsTests.cs
  Octokit.sln.DotSettings
  Octokit/Clients/IRepositoriesClient.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Clients/RepositoryForksClient.cs
  Octokit/Helpers/AcceptHeaders.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Request/SearchRepositoriesRequest.cs
  Octokit/Models/Response/Repository.cs
  Octokit/Models/Response/RepositoryTopics.cs
Labels: under-review

#2306 cleanup some mentions of master branch in codebase
  Octokit/Helpers/ReferenceExtensions.cs
  README.md
  ReleaseNotes.md
Labels: category: housekeeping
