Repository octokit/octokit.net, pull requests merged in 2022-07, with the labels that each got.

#2453 Add method to check if repo vulnerability alerts are enabled
  Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
  Octokit/Clients/IRepositoriesClient.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Helpers/ApiUrls.cs
Labels: category: feature

#2378 fix: links into github documentation
  docs/getting-started.md
Labels: category: docs-and-samples

#2424 Update permissions based on GitHub documentation
  Octokit/Models/Request/Permission.cs
Labels: category: feature

#2476 Add AutoMerge and add MergeOptions to NewRepository object
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit/Models/Request/NewRepository.cs
  Octokit/Models/Request/RepositoryUpdate.cs
  Octokit/Models/Response/Repository.cs
Labels: category: feature

#2413 Deployment task is arbitrary string value
  Octokit.Tests/Models/DeploymentTests.cs
  Octokit/Models/Request/NewDeployment.cs
  Octokit/Models/Response/Deployment.cs
Labels: category: feature, improvement, category: breaking-change

#2391 Adds the slug field to the GitHubApp response object
  Octokit/Models/Response/GitHubApp.cs
Labels: category: feature, improvement

#2482 Adding squash title to NewRepository
  Octokit/Models/Request/NewRepository.cs
Labels: category: feature

#2478 feat: Fixes GitHubApp response object code docs typo
  Octokit/Models/Response/GitHubApp.cs
Labels: category: docs-and-samples

#2487 Update organizations-related `GetAllForUser` method docs to make it clear that only public memberships are returned
  Octokit/Clients/IOrganizationsClient.cs
  Octokit/Clients/OrganizationsClient.cs
Labels: category: docs-and-samples

#2486 Trimming trailing slashes from user passed paths
  Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
  Octokit/Helpers/ApiUrls.cs
Labels: category: bug

#2389 New pull request from existing issue
  Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
  Octokit/Models/Request/NewPullRequest.cs
Labels: category: feature

#2501 Fix null reference access when ContentType is null
  Octokit.Tests/Exceptions/ApiExceptionTests.cs
  Octokit/Exceptions/ApiException.cs
Labels: category: bug

#2494 Adding 4 new Reaction delete routes and obsoleting existing routes
  Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/IssueCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/IssueReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
  Octokit/Clients/CommitCommentReactionsClient.cs
  Octokit/Clients/ICommitCommentReactionsClient.cs
  Octokit/Clients/IIssueCommentReactionsClient.cs
  Octokit/Clients/IIssueReactionsClient.cs
  Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/IssueCommentReactionsClient.cs
  Octokit/Clients/IssueReactionsClient.cs
  Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/ReactionsClient.cs
  Octokit/Helpers/ApiUrls.cs
Labels: category: feature

#2492 Add missing properties to RepositoryUpdate
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests.Integration/GitHubClientTestBase.cs
  Octokit.Tests.Integration/SelfTests.cs
  Octokit.Tests/Models/RepositoryUpdateTests.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Models/Request/RepositoryUpdate.cs
Labels: category: feature

#2511 Updates and fixes for tests, changing master to main and adding flaky tests marker
  Octokit.Tests.Integration/Clients/BlobClientTests.cs
  Octokit.Tests.Integration/Clients/CommitCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/CommitStatusClientTests.cs
  Octokit.Tests.Integration/Clients/CommitsClientTests.cs
  Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs
  Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs
  Octokit.Tests.Integration/Clients/IssueCommentsClientTests.cs
  Octokit.Tests.Integration/Clients/IssuesClientTests.cs
  Octokit.Tests.Integration/Clients/MergingClientTests.cs
  Octokit.Tests.Integration/Clients/ProjectCardsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewCommentReactionsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewRequestsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
  Octokit.Tests.Integration/Clients/ReferencesClientTests.cs
  Octokit.Tests.Integration/Clients/ReleasesClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryBranchesClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryCommentsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryDeployKeysClientTests.cs
  Octokit.Tests.Integration/Clients/SearchClientTests.cs
  Octokit.Tests.Integration/Clients/StatisticsClientTests.cs
  Octokit.Tests.Integration/Clients/TagsClientTests.cs
  Octokit.Tests.Integration/Clients/TreeClientTests.cs
  Octokit.Tests.Integration/Clients/WatchedClientTests.cs
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests.Integration/Helpers/GithubClientExtensions.cs
  Octokit.Tests.Integration/Helpers/PaidAccountTestAttribute.cs
  Octokit.Tests.Integration/Helpers/ReferenceExtensionsTests.cs
  Octokit.Tests.Integration/Helpers/RepositorySetupHelper.cs
  Octokit.Tests.Integration/PotentiallyFlakyTestAttribute.cs
  Octokit.Tests.Integration/Reactive/ObservableCheckRunsClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableCheckSuitesClientTests.cs
Labels: category: housekeeping

#2514 Removing private repositories limit exception
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Exceptions/PrivateRepositoryQuotaExceededException.cs
Labels: category: housekeeping
