Repository octokit/octokit.net, pull requests merged in 2022-09, with the labels that each got.

#2559 Fix failure with 201 status code on adding a collaborator
  Octokit.Reactive/Clients/IObservableRepoCollaboratorsClient.cs
  Octokit.Reactive/Clients/ObservableRepoCollaboratorsClient.cs
  Octokit.Tests/Clients/RepoCollaboratorsClientTests.cs
  Octokit/Clients/IRepoCollaboratorsClient.cs
  Octokit/Clients/RepoCollaboratorsClient.cs
Labels: category: breaking-change

#2563 [Releases]Added support for generating release notes
  Octokit.Reactive/Clients/IObservableReleasesClient.cs
  Octokit.Reactive/Clients/ObservableReleasesClient.cs
  Octokit.Tests/Clients/ReleasesClientTests.cs
  Octokit/Clients/IReleasesClient.cs
  Octokit/Clients/ReleasesClient.cs
  Octokit/Models/Request/GenerateReleaseNotesRequest.cs
  Octokit/Models/Response/GeneratedReleaseNotes.cs
  docs/releases.md
Labels: category: feature

#2551 Adding Packages Api
  Octokit.Reactive/Clients/IObservablePackageVersionsClient.cs
  Octokit.Reactive/Clients/IObservablePackagesClient.cs
  Octokit.Reactive/Clients/ObservablePackageVersionsClient.cs
  Octokit.Reactive/Clients/ObservablePackagesClient.cs
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit.Tests.Integration/Clients/PackageVersionsClientTests.cs
  Octokit.Tests.Integration/Clients/PackagesClientTests.cs
  Octokit.Tests/Clients/PackageVersionsClientTests.cs
  Octokit.Tests/Clients/PackagesClientTests.cs
  Octokit.Tests/Reactive/ObservablePackageVersionsTests.cs
  Octokit.Tests/Reactive/ObservablePackagesTests.cs
  Octokit/Clients/IPackageVersionsClient.cs
  Octokit/Clients/IPackagesClient.cs
  Octokit/Clients/PackageVersionsClient.cs
  Octokit/Clients/PackagesClient.cs
  Octokit/GitHubClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Helpers/Ensure.cs
  Octokit/Helpers/EnumExtensions.cs
  Octokit/Helpers/ParameterBuilder.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Common/PackageType.cs
  Octokit/Models/Common/PackageVersionState.cs
  Octokit/Models/Common/PackageVisibility.cs
  Octokit/Models/Response/Package.cs
  Octokit/Models/Response/PackageVersion.cs
Labels: category: feature, model-change, route-change

#2560 Added missing fields for deployments API
  Octokit.Tests.Conventions/Octokit.Tests.Conventions.csproj
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Models/DeploymentTests.cs
  Octokit.Tests/Octokit.Tests.csproj
  Octokit/Models/Response/Deployment.cs
Labels: category: feature

#2556 Adding credential-authorization get endpoints
  Octokit.AsyncPaginationExtension/Extensions.cs
  Octokit.Reactive/Clients/IObservableOrganizationsClient.cs
  Octokit.Reactive/Clients/ObservableOrganizationsClient.cs
  Octokit.Tests/Clients/OrganizationsClientTests.cs
  Octokit.Tests/Reactive/ObservableOrganizationsClientTests.cs
  Octokit/Clients/IOrganizationsClient.cs
  Octokit/Clients/OrganizationsClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Response/OrganizationCredential.cs
Labels: category: feature

#2573 Remove `/en` slug in docs.github.com links (and stop VSCode from formatting on save)
  .github/workflows/codeql-analysis.yml
  .vscode/settings.json
  Octokit.Reactive/Clients/Enterprise/IObservableEnterpriseClient.cs
  Octokit.Reactive/Clients/Enterprise/IObservableEnterprisePreReceiveHooksClient.cs
  Octokit.Reactive/Clients/Enterprise/ObservableEnterpriseClient.cs
  Octokit.Reactive/Clients/Enterprise/ObservableEnterprisePreReceiveHooksClient.cs
  Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableReleasesClient.cs
  Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableReleasesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit/Clients/CommitCommentReactionsClient.cs
  Octokit/Clients/Enterprise/EnterpriseClient.cs
  Octokit/Clients/Enterprise/EnterprisePreReceiveHooksClient.cs
  Octokit/Clients/Enterprise/IEnterpriseClient.cs
  Octokit/Clients/Enterprise/IEnterprisePreReceiveHooksClient.cs
  Octokit/Clients/ICommitCommentReactionsClient.cs
  Octokit/Clients/IIssueCommentReactionsClient.cs
  Octokit/Clients/IIssueReactionsClient.cs
  Octokit/Clients/IOrganizationMembersClient.cs
  Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/IReleasesClient.cs
  Octokit/Clients/IRepositoriesClient.cs
  Octokit/Clients/IssueReactionsClient.cs
  Octokit/Clients/OrganizationMembersClient.cs
  Octokit/Clients/PackagesClient.cs
  Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/ReleasesClient.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Exceptions/SecondaryRateLimitExceededException.cs
  Octokit/GitHubClient.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Request/GenerateReleaseNotesRequest.cs
  Octokit/Models/Response/GeneratedReleaseNotes.cs
Labels: category: docs-and-samples

#2574 Splitting out the misc client into separate clients as per current documentation
  Octokit.Reactive/Clients/IObservableEmojiClient.cs
  Octokit.Reactive/Clients/IObservableGitIgnoreClient.cs
  Octokit.Reactive/Clients/IObservableLicensesClient.cs
  Octokit.Reactive/Clients/IObservableMarkdownClient.cs
  Octokit.Reactive/Clients/IObservableMetaClient.cs
  Octokit.Reactive/Clients/IObservableMiscellaneousClient.cs
  Octokit.Reactive/Clients/IObservableRateLimitClient.cs
  Octokit.Reactive/Clients/ObservableEmojiClient.cs
  Octokit.Reactive/Clients/ObservableGitIgnoreClient.cs
  Octokit.Reactive/Clients/ObservableLicensesClient.cs
  Octokit.Reactive/Clients/ObservableMarkdownClient.cs
  Octokit.Reactive/Clients/ObservableMetaClient.cs
  Octokit.Reactive/Clients/ObservableMiscellaneousClient.cs
  Octokit.Reactive/Clients/ObservableRateLimitClient.cs
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit.Tests.Integration/Clients/EmojisClientTests.cs
  Octokit.Tests.Integration/Clients/GitIgnoreClientTests.cs
  Octokit.Tests.Integration/Clients/LicensesClientTests.cs
  Octokit.Tests.Integration/Clients/MarkdownClientTests.cs
  Octokit.Tests.Integration/Clients/MetaClientTests.cs
  Octokit.Tests.Integration/Clients/RateLimitClientTests.cs
  Octokit.Tests/Clients/EmojisClientTests.cs
  Octokit.Tests/Clients/LicensesClientTests.cs
  Octokit.Tests/Clients/MarkdownClientTests.cs
  Octokit.Tests/Clients/MetaClientTests.cs
  Octokit.Tests/Clients/RateLimitClientTests.cs
  Octokit.Tests/Reactive/ObservableEmojiClientTests.cs
  Octokit.Tests/Reactive/ObservableGitIgnoreClientTests.cs
  Octokit.Tests/Reactive/ObservableLicensesClientTests.cs
  Octokit.Tests/Reactive/ObservableMarkdownClientTests.cs
  Octokit.Tests/Reactive/ObservableMetaClientTests.cs
  Octokit.Tests/Reactive/ObservableRateLimitClientTests.cs
  Octokit/Clients/EmojisClient.cs
  Octokit/Clients/GitIgnoreClient.cs
  Octokit/Clients/IEmojisClient.cs
  Octokit/Clients/IGitIgnoreClient.cs
  Octokit/Clients/ILicensesClient.cs
  Octokit/Clients/IMarkdownClient.cs
  Octokit/Clients/IMetaClient.cs
  Octokit/Clients/IMiscellaneousClient.cs
  Octokit/Clients/IRateLimitClient.cs
  Octokit/Clients/LicensesClient.cs
  Octokit/Clients/MarkdownClient.cs
  Octokit/Clients/MetaClient.cs
  Octokit/Clients/MiscellaneousClient.cs
  Octokit/Clients/RateLimitClient.cs
  Octokit/GitHubClient.cs
  Octokit/IGitHubClient.cs
Labels: category: housekeeping

#2577 Fix deserializing of Emoji types
  Octokit.Tests/Clients/MiscellaneousClientTests.cs
  Octokit/Clients/MiscellaneousClient.cs
  Octokit/Http/AssignableExtensions.cs
  Octokit/Http/JsonHttpPipeline.cs
Labels: category: bug

#2579 Fixes the meta dto and meta tests so they pass and are fully the same…
  Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs
  Octokit.Tests/Clients/MiscellaneousClientTests.cs
  Octokit/Models/Response/Meta.cs
Labels: category: bug

#2581 updates tests to include new fields
  Octokit.Tests/Clients/MetaClientTests.cs
Labels: category: bug

#2584 ci: revert 0d6b7c41 and 30fdeca1
  .github/workflows/netcore.yml
  .github/workflows/publish.yml
Labels: category: housekeeping
