Repository octokit/octokit.net, pull requests merged in 2022-12, with the labels that each got.

#2625 Add missing properties for meta and app payloads
  Octokit.Tests/Clients/MetaClientTests.cs
  Octokit.Tests/Clients/MiscellaneousClientTests.cs
  Octokit/Models/Response/GitHubApp.cs
  Octokit/Models/Response/InstallationPermissions.cs
  Octokit/Models/Response/Meta.cs
Labels: Type: Breaking change, Type: Feature

#2630 Updates the stale action to use the new status labels
  .github/workflows/stale.yml
Labels: Priority: Normal, Type: Maintenance

#2315 Fixes #2143 - Support listing branch/pr per commit
  Octokit.Reactive/Clients/IObservableRepositoryCommitsClients.cs
  Octokit.Reactive/Clients/ObservableRepositoryCommitsClients.cs
  Octokit.Tests/Clients/RespositoryCommitsClientTests.cs
  Octokit.Tests/Reactive/ObservableRepositoryCommitsClientTests.cs
  Octokit/Clients/IRepositoryCommitsClient.cs
  Octokit/Clients/RepositoryCommitsClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Response/CommitPullRequest.cs
Labels: Priority: High, Type: Feature
