Repository octokit/octokit.net, pull requests merged in 2022-05, with the labels that each got.

#2441 Creates the config file for stalebot to help us clean up old/inactive issues
  .github/stale.yml
Labels: category: housekeeping

#2442 Adds stale bot functionality via action and removes the stalebot config
  .github/stale.yml
  .github/workflows/stale.yml
Labels: category: housekeeping

#2443 Configure the project for GitHub Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .vscode/tasks.json
Labels: skip-release-notes, category: housekeeping

#2381 Add Draft to MergeableState enum
  Octokit/Models/Response/PullRequest.cs
Labels: category: feature
