Repository octokit/octokit.net, pull requests merged in 2022-08, with the labels that each got.

#2519 move deprecation warning from subscribers_count to watchers_count.
  Octokit/Models/Response/Repository.cs
Labels: category: docs-and-samples

#2520 [WIP] update code docs for SetRequestTimeout
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit/GitHubClient.cs
  Octokit/Http/Connection.cs
  Octokit/Http/IConnection.cs
  Octokit/Http/IHttpClient.cs
  Octokit/IGitHubClient.cs
Labels: category: docs-and-samples

#2521 Drop support for .NET 4.6
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit.Tests.Integration/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs
  Octokit/Models/Request/RepositoryUpdate.cs
  Octokit/Octokit.csproj
  build/Context.cs
  build/Lifetime.cs
  build/Tasks/Build.cs
  build/Tasks/ConventionTests.cs
  build/Tasks/IntegrationTests.cs
  build/Tasks/Package.cs
  build/Tasks/Restore.cs
  build/Tasks/UnitTests.cs
  build/Tasks/ValidateLINQPadSamples.cs
  build/Utilities/ToolInstaller.cs
Labels: category: housekeeping, dependencies, category: breaking-change

#2524 Fixing issues with two factor authentication overload and certain endpoints
  Octokit.Tests/Clients/RepositoriesClientTests.cs
  Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Clients/RepositoryBranchesClient.cs
Labels: category: bug

#2516 Add AsyncPaginationExtensions
  Octokit.AsyncPaginationExtension/Extensions.cs
  Octokit.AsyncPaginationExtension/IPaginatedList.cs
  Octokit.AsyncPaginationExtension/LazyList.cs
  Octokit.AsyncPaginationExtension/Octokit.AsyncPaginationExtension.csproj
  Octokit.AsyncPaginationExtension/PaginatedList.cs
  Octokit.Tests/AsyncEnumerableExtensionTests.cs
  Octokit.Tests/Octokit.Tests.csproj
  Octokit.sln
Labels: category: feature

#2535 Fixing the use of the binary formatter in net461 so all unit tests now pass.
  Octokit.Tests/Clients/UsersClientTests.cs
  Octokit.Tests/Exceptions/ApiExceptionTests.cs
  Octokit.Tests/Exceptions/ApiValidationExceptionTests.cs
  Octokit.Tests/Exceptions/RateLimitExceededExceptionTests.cs
  Octokit.Tests/Helpers/BindaryFormatterHelpers.cs
  Octokit.Tests/Http/RateLimitTests.cs
Labels: category: housekeeping

#2533 feat: implement getting failed org invites
  Octokit.Reactive/Clients/IObservableOrganizationMembersClient.cs
  Octokit.Reactive/Clients/ObservableOrganizationMembersClient.cs
  Octokit.Tests.Integration/Clients/OrganizationMembersClientTests.cs
  Octokit/Clients/IOrganizationMembersClient.cs
  Octokit/Clients/OrganizationMembersClient.cs
  Octokit/Helpers/ApiUrls.cs
Labels: category: feature

#2537 Add generators project for source generation
  .devcontainer/Dockerfile
  .github/workflows/netcore.yml
  .github/workflows/publish.yml
  .vscode/launch.json
  Octokit.AsyncPaginationExtension/Extensions.cs
  Octokit.AsyncPaginationExtension/Octokit.AsyncPaginationExtension.csproj
  Octokit.Generators/AsyncPaginationExtensionsGenerator.cs
  Octokit.Generators/Generator.cs
  Octokit.Generators/Octokit.Generators.csproj
  Octokit.Generators/README.md
  Octokit.sln
Labels: category: docs-and-samples, category: feature

#2541 Add documentation on how to create a branch
  docs/git-database.md
Labels: category: docs-and-samples

#2538 Tidying up DefineConstants
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit.Tests/Fixtures/EmbeddedResource.cs
  Octokit.Tests/Fixtures/Fixtures.cs
  Octokit.Tests/Http/RateLimitTests.cs
  Octokit.Tests/Octokit.Tests.csproj
  Octokit.Tests/SelfTests.cs
  Octokit/Exceptions/AbuseException.cs
  Octokit/Exceptions/ApiException.cs
  Octokit/Exceptions/ApiValidationException.cs
  Octokit/Exceptions/AuthorizationException.cs
  Octokit/Exceptions/ForbiddenException.cs
  Octokit/Exceptions/InvalidGitIgnoreTemplateException.cs
  Octokit/Exceptions/LegalRestrictionException.cs
  Octokit/Exceptions/LoginAttemptsExceededException.cs
  Octokit/Exceptions/NotFoundException.cs
  Octokit/Exceptions/PullRequestMismatchException.cs
  Octokit/Exceptions/PullRequestNotMergeableException.cs
  Octokit/Exceptions/RateLimitExceededException.cs
  Octokit/Exceptions/RepositoryExistsException.cs
  Octokit/Exceptions/RepositoryFormatException.cs
  Octokit/Exceptions/SecondaryRateLimitExceededException.cs
  Octokit/Exceptions/TwoFactorAuthorizationException.cs
  Octokit/Exceptions/TwoFactorChallengeFailedException.cs
  Octokit/Exceptions/TwoFactorRequiredException.cs
  Octokit/Exceptions/UserIsLastOwnerOfOrganizationException.cs
  Octokit/Exceptions/UserIsNotMemberOfOrganizationException.cs
  Octokit/Exceptions/UserIsOrganizationMemberException.cs
  Octokit/Helpers/ReflectionExtensions.cs
  Octokit/Http/Connection.cs
  Octokit/Http/HttpClientAdapter.cs
  Octokit/Http/RateLimit.cs
  Octokit/Models/Response/ApiError.cs
  Octokit/Models/Response/ApiErrorDetail.cs
  Octokit/Octokit.csproj
  Octokit/SimpleJson.cs
Labels: category: housekeeping

#2539 Adding seats and filled seats to plan response.
  Octokit.Tests.Integration/Clients/OrganizationClientTests.cs
  Octokit/Models/Response/Plan.cs
Labels: category: feature, unexpected-response-shape

#2543 add active lock reason to PR
  Octokit.Reactive/Clients/IObservableIssuesClient.cs
  Octokit.Reactive/Clients/IObservableLockUnlockClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestsClient.cs
  Octokit.Reactive/Clients/ObservableIssuesClient.cs
  Octokit.Reactive/Clients/ObservableLockUnlockClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestsClient.cs
  Octokit.Tests.Integration/Clients/IssuesClientTests.cs
  Octokit.Tests.Integration/Clients/IssuesEventsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestsClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableIssuesClientTests.cs
  Octokit.Tests/Clients/IssuesClientTests.cs
  Octokit.Tests/Reactive/ObservableIssuesClientTests.cs
  Octokit/Clients/IIssuesClient.cs
  Octokit/Clients/ILockUnlockClient.cs
  Octokit/Clients/IPullRequestsClient.cs
  Octokit/Clients/IssuesClient.cs
  Octokit/Clients/LockUnlockClient.cs
  Octokit/Clients/PullRequestsClient.cs
  Octokit/Models/Response/PullRequest.cs
  docs/issues.md
Labels: category: feature, category: breaking-change
