Repository octokit/octokit.net, pull requests merged in 2022-11, with the labels that each got.

#2604 Add issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
Labels: Type: Maintenance

#2612 Add PR templates
  .github/pull_request_template.md
Labels: Type: Maintenance

#2600 Adding repo allowupdatebranch
  Octokit/Models/Request/RepositoryUpdate.cs
  Octokit/Models/Response/Repository.cs
Labels: Priority: High, Type: Feature

#2613 Added Environments API - GetAll list only feature
  Octokit.Reactive/Clients/IObservableRepositoriesClient.cs
  Octokit.Reactive/Clients/IObservableRepositoryDeployEnvironmentsClient.cs
  Octokit.Reactive/Clients/ObservableEnvironmentsClient.cs
  Octokit.Reactive/Clients/ObservableRepositoriesClient.cs
  Octokit.Tests/Clients/EnvironmentsClientTests.cs
  Octokit/Clients/DeploymentEnvironmentsClient.cs
  Octokit/Clients/IRepositoriesClient.cs
  Octokit/Clients/IRepositoryDeployEnvironmentsClient.cs
  Octokit/Clients/RepositoriesClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Request/ApiOptions.cs
  Octokit/Models/Response/DeploymentEnvironment.cs
  Octokit/Models/Response/DeploymentEnvironmentsResponse.cs
Labels: Priority: Normal, Type: Feature

#2608 Fixed a bug that content cannot be retrieved if "#" is included in a file or folder name.
  Octokit.Tests/Helpers/StringExtensionsTests.cs
  Octokit/Helpers/StringExtensions.cs
Labels: Priority: Normal, Type: Bug
