Repository octokit/octokit.net, pull requests merged in 2022-10, with the labels that each got.

#2591 Base classes need protected setters, ActivityPayload had privates
  Octokit.Tests/Models/CheckSuiteEventTests.cs
  Octokit/Models/Response/ActivityPayloads/ActivityPayload.cs
Labels: category: bug

#2592 Use correct methods and URL to generate release notes
  Octokit.Tests/Clients/ReleasesClientTests.cs
  Octokit/Clients/ReleasesClient.cs
  Octokit/Helpers/ApiUrls.cs
  docs/releases.md
Labels: category: bug

#2575 Add strong name signing
  Directory.Build.props
  Octokit.Tests.Integration/Octokit.Tests.Integration.csproj
  Octokit/Octokit.csproj
  Octokit/Properties/AssemblyInfo.cs
  build/Build.csproj
  key.snk
Labels: category: housekeeping, under-review, category: breaking-change

#2585 Add missing properties to `IssueEvent`.
  Octokit/Models/Response/DismissedReviewInfo.cs
  Octokit/Models/Response/IssueEvent.cs
  Octokit/Models/Response/Milestone.cs
Labels: category: feature
