Repository octokit/octokit.net, pull requests merged in 2023-01, with the labels that each got.

#2655 Remove instances of lower-case h
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Response/PagesBuild.cs
  Octokit/Models/Response/PullRequestReview.cs
  Octokit/Models/Response/PullRequestReviewComment.cs
  docs/getting-started.md
Labels: Type: Maintenance

#2633 update models with updated permission enum
  Octokit.Reactive/Clients/IObservableTeamsClient.cs
  Octokit.Reactive/Clients/ObservableTeamsClient.cs
  Octokit.Tests.Conventions/PreviewsTests.cs
  Octokit.Tests.Integration/Clients/TeamsClientTests.cs
  Octokit.Tests.Integration/Helper.cs
  Octokit.Tests.Integration/Helpers/ObservableGithubClientExtensions.cs
  Octokit.Tests.Integration/Helpers/TeamContext.cs
  Octokit.Tests.Integration/Reactive/ObservableTeamsClientTests.cs
  Octokit.Tests/Clients/TeamsClientTests.cs
  Octokit.Tests/SimpleJsonSerializerTests.cs
  Octokit/Clients/ITeamsClient.cs
  Octokit/Clients/TeamsClient.cs
  Octokit/Helpers/AcceptHeaders.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Http/ApiConnection.cs
  Octokit/Http/Connection.cs
  Octokit/Http/IApiConnection.cs
  Octokit/Http/IConnection.cs
  Octokit/Models/Request/NewTeam.cs
  Octokit/Models/Request/Permission.cs
  Octokit/Models/Request/UpdateTeam.cs
  Octokit/Models/Response/Team.cs
  Octokit/Models/Response/TeamRepository.cs
  docs/teams.md
Labels: Type: Breaking change

#2660 Happy New Year!
  README.md
Labels: Type: Maintenance

#2657 Add pending WorkflowRunStatus
  Octokit/Models/Response/WorkflowRunStatus.cs
Labels: Priority: Normal, Type: Bug
