Repository octokit/octokit.net, pull requests merged in 2023-02, with the labels that each got.

#2666 Removes the old implementation of sourcelink and uses the newer one present in the .net SDK
  .config/dotnet-tools.json
  .github/workflows/netcore.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  Octokit.Reactive/Octokit.Reactive.csproj
  Octokit/Octokit.csproj
  README.md
  build.ps1
  build/Context.cs
  build/Lifetime.cs
  build/Tasks/Build.cs
  build/Tasks/Default.cs
  build/Tasks/TestSourceLink.cs
  docs/debugging-source.md
  docs/shipping-releases.md
Labels: Priority: High, Type: Bug, Type: Maintenance, dependencies

#2648 Response caching
  Octokit.Tests/Caching/CachedResponseTests.cs
  Octokit.Tests/Caching/CachingHttpClientTests.cs
  Octokit.Tests/GitHubClientTests.cs
  Octokit.Tests/Helpers/ApiInfoComparer.cs
  Octokit.Tests/Helpers/CollectionComparer.cs
  Octokit.Tests/Helpers/RateLimitComparer.cs
  Octokit.Tests/Helpers/ResponseComparer.cs
  Octokit.Tests/Helpers/StringKeyedDictionaryComparer.cs
  Octokit.Tests/Http/ConnectionTests.cs
  Octokit/Caching/CachedResponse.cs
  Octokit/Caching/CachingHttpClient.cs
  Octokit/Caching/IResponseCache.cs
  Octokit/GitHubClient.cs
  Octokit/Http/Connection.cs
  Octokit/Http/IConnection.cs
Labels: Priority: Normal, Type: Feature

#2665 Add StateReason to IssueUpdate
  Octokit.Tests.Integration/Clients/IssuesClientTests.cs
  Octokit.Tests/Models/IssueTest.cs
  Octokit/Models/Request/IssueRequest.cs
  Octokit/Models/Request/IssueUpdate.cs
  Octokit/Models/Response/Issue.cs
Labels: Priority: High, Type: Bug
