Repository octokit/octokit.net, pull requests merged in 2023-10, with the labels that each got.

#2792 [fix] Bump GitVersion.Tool
  build/Lifetime.cs
Labels: Type: Bug

#2794 [feat]: Adding repository variables
  Octokit.Reactive/Clients/IObservableRepositoryActionsClient.cs
  Octokit.Reactive/Clients/IObservableRepositoryVariablesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryActionsClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryVariablesClient.cs
  Octokit.Tests/Clients/RepositoryVariablesClientTests.cs
  Octokit/Clients/IRepositoryActionsClient.cs
  Octokit/Clients/IRepositoryVariablesClient.cs
  Octokit/Clients/RepositoryActionsClient.cs
  Octokit/Clients/RepositoryVariablesClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Request/Variable.cs
  Octokit/Models/Response/RepositoryVariable.cs
  Octokit/Models/Response/RepositoryVariablesCollection.cs
Labels: Type: Feature

#2795 [feat]: Adding missing properties to PushEventPayload
  Octokit.Tests/Clients/EventsClientTests.cs
  Octokit/Models/Response/ActivityPayloads/PushEventPayload.cs
Labels: Type: Feature, hacktoberfest

#2799 [feat]: Add RenameBranch method to RepositoryBranchesClient
  Octokit.Reactive/Clients/IObservableRepositoryBranchesClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryBranchesClient.cs
  Octokit.Tests/Clients/RepositoryBranchesClientTests.cs
  Octokit/Clients/IRepositoryBranchesClient.cs
  Octokit/Clients/RepositoryBranchesClient.cs
  Octokit/Helpers/ApiUrls.cs
  build/Utilities/BuildVersion.cs
Labels: Type: Feature, hacktoberfest

#2806 [BREAKING CHANGE]: Removes the .NET 5.0 support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/netcore.yml
  .github/workflows/publish.yml
Labels: Type: Breaking change, Type: Maintenance, hacktoberfest
