Repository octokit/octokit.net, pull requests merged in 2024-06, with the labels that each got.

#2928 #2927: comment id model update to long instead of int
  Octokit.Reactive/Clients/IObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableGistCommentsClient.cs
  Octokit.Reactive/Clients/IObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservableIssueCommentsClient.cs
  Octokit.Reactive/Clients/IObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/IObservablePullRequestReviewCommentsClient.cs
  Octokit.Reactive/Clients/IObservableRepositoryCommentsClient.cs
  Octokit.Reactive/Clients/ObservableCommitCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableGistCommentsClient.cs
  Octokit.Reactive/Clients/ObservableIssueCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservableIssueCommentsClient.cs
  Octokit.Reactive/Clients/ObservableIssueReactionsClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestReviewCommentReactionsClient.cs
  Octokit.Reactive/Clients/ObservablePullRequestReviewCommentsClient.cs
  Octokit.Reactive/Clients/ObservableRepositoryCommentsClient.cs
  Octokit.Tests.Integration/Clients/IssueCommentsClientTests.cs
  Octokit.Tests.Integration/Clients/PullRequestReviewCommentsClientTests.cs
  Octokit.Tests.Integration/Clients/RepositoryCommentsClientTests.cs
  Octokit.sln
  Octokit/Clients/AuthorizationsClient.cs
  Octokit/Clients/CheckSuitesClient.cs
  Octokit/Clients/CommitCommentReactionsClient.cs
  Octokit/Clients/Enterprise/EnterprisePreReceiveEnvironmentsClient.cs
  Octokit/Clients/Enterprise/EnterprisePreReceiveHooksClient.cs
  Octokit/Clients/GistCommentsClient.cs
  Octokit/Clients/GistsClient.cs
  Octokit/Clients/ICommitCommentReactionsClient.cs
  Octokit/Clients/IGistCommentsClient.cs
  Octokit/Clients/IIssueCommentReactionsClient.cs
  Octokit/Clients/IIssueCommentsClient.cs
  Octokit/Clients/IIssueReactionsClient.cs
  Octokit/Clients/IPullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/IPullRequestReviewCommentsClient.cs
  Octokit/Clients/IRepositoryCommentsClient.cs
  Octokit/Clients/IssueCommentReactionsClient.cs
  Octokit/Clients/IssueCommentsClient.cs
  Octokit/Clients/IssueReactionsClient.cs
  Octokit/Clients/IssuesEventsClient.cs
  Octokit/Clients/NotificationsClient.cs
  Octokit/Clients/ProjectCardsClient.cs
  Octokit/Clients/ProjectColumnsClient.cs
  Octokit/Clients/ProjectsClient.cs
  Octokit/Clients/PullRequestReviewCommentReactionsClient.cs
  Octokit/Clients/PullRequestReviewCommentsClient.cs
  Octokit/Clients/PullRequestReviewsClient.cs
  Octokit/Clients/ReleasesClient.cs
  Octokit/Clients/RepositoryCommentsClient.cs
  Octokit/Clients/TeamsClient.cs
  Octokit/Clients/UserGpgKeysClient.cs
  Octokit/Clients/UserKeysClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/Models/Request/PullRequestReviewCommentReplyCreate.cs
  Octokit/Models/Response/CommitComment.cs
  Octokit/Models/Response/GistComment.cs
  Octokit/Models/Response/IssueComment.cs
  Octokit/Models/Response/PullRequestReviewComment.cs
  Octokit/Models/Response/Reaction.cs
  Octokit/Models/Response/TeamRepository.cs
Labels: Type: Breaking change, Type: Bug

#2932 feat: Implement dependency review and dependency submission APIs
  Octokit.Reactive/Clients/IObservableDependencyGraphClient.cs
  Octokit.Reactive/Clients/IObservableDependencyReviewClient.cs
  Octokit.Reactive/Clients/IObservableDependencySubmissionClient.cs
  Octokit.Reactive/Clients/ObservableDependencyGraphClient.cs
  Octokit.Reactive/Clients/ObservableDependencyReviewClient.cs
  Octokit.Reactive/Clients/ObservableDependencySubmissionClient.cs
  Octokit.Reactive/IObservableGitHubClient.cs
  Octokit.Reactive/ObservableGitHubClient.cs
  Octokit.Tests.Integration/Clients/DependencyReviewClientTests.cs
  Octokit.Tests.Integration/Clients/DependencySubmissionClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableDependencyReviewClientTests.cs
  Octokit.Tests.Integration/Reactive/ObservableDependencySubmissionClientTests.cs
  Octokit.Tests/Clients/DependencyGraphClientTests.cs
  Octokit.Tests/Clients/DependencyReviewClientTests.cs
  Octokit.Tests/Clients/DependencySubmissionClientTests.cs
  Octokit.Tests/Models/DependencyDiffTests.cs
  Octokit.Tests/Models/DependencySnapshotSubmissionTests.cs
  Octokit.Tests/Reactive/ObservableDependencyGraphClientTests.cs
  Octokit.Tests/Reactive/ObservableDependencyReviewClientTests.cs
  Octokit.Tests/Reactive/ObservableDependencySubmissionClientTests.cs
  Octokit/Clients/DependencyGraphClient.cs
  Octokit/Clients/DependencyReviewClient.cs
  Octokit/Clients/DependencySubmissionClient.cs
  Octokit/Clients/IDependencyGraphClient.cs
  Octokit/Clients/IDependencyReviewClient.cs
  Octokit/Clients/IDependencySubmissionClient.cs
  Octokit/GitHubClient.cs
  Octokit/Helpers/ApiUrls.cs
  Octokit/IGitHubClient.cs
  Octokit/Models/Request/NewDependencySnapshot.cs
  Octokit/Models/Request/NewDependencySnapshotDetector.cs
  Octokit/Models/Request/NewDependencySnapshotJob.cs
  Octokit/Models/Request/NewDependencySnapshotManifest.cs
  Octokit/Models/Request/NewDependencySnapshotManifestFile.cs
  Octokit/Models/Request/NewDependencySnapshotResolvedDependency.cs
  Octokit/Models/Response/ChangeType.cs
  Octokit/Models/Response/DependencyDiff.cs
  Octokit/Models/Response/DependencySnapshotSubmission.cs
  Octokit/Models/Response/Scope.cs
Labels: Type: Feature

#2865 [Feat] Add Advanced Security Properties to Repository Get/Update
  Octokit/Models/Common/Status.cs
  Octokit/Models/Request/RepositoryUpdate.cs
  Octokit/Models/Request/SecurityAndAnalysisRequest.cs
  Octokit/Models/Response/Repository.cs
  Octokit/Models/Response/SecurityAndAnalysis.cs
Labels: Status: Blocked, Type: Breaking change, Type: Feature
